name: Build for PC (SDL2)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - run:  bash compile-docker.sh TARGET_PC_SDL2
